### ISSUE TITLE
Not working in the latest VSC

### ISSUE THREAD

**Issue by zonyitoo** [xaverh/vscode-clang-format-provider#1]
VSC version: 0.10.6 (0.10.6)

It has no response after I called the `beautify` command from the command palette in a `.cpp` file.

**Comment by xaverh** [comment]
`beautify`? I don't have the command on my palette. Can you be more specific? On both my Windows and my Linux machine it's still working with 0.10.6.

**Comment by zonyitoo** [comment]
Hmm, maybe this plugin haven't registered in beautify plugin. My fault.
But I have already set format on save to `true`, but nothing happened after I saved the file.

**Comment by f0rmiga** [comment]
Not working here, VSC 1.0.0.

**Comment by xaverh** [comment]
Could you be more precise? Which feature is not working? Because there is no `beautify` command in this extension?

**Comment by f0rmiga** [comment]
Sorry, it is not related to beautify. The tool itself is not working. Nothing happens when trying to format.

**Comment by ioachim** [comment]
About VSC 1.0.0, there is some change in the behavior of `child_process`, as for some reason, the `clang-format` process isn't recieving what I send to `stdio`... I'll keep working on that issue

**Comment by ioachim** [comment]
@xaverh Debugging, I found the problem to be is the default fallback style of `none`, as it makes the tool not to format anything if you don't specify a style. I confirmed it works by setting `clang-format.fallbackStyle` to the different possible values.

I think you should change the default.

**Comment by xaverh** [comment]
I set "LLVM" as fallback style (which I think is also what the command-line version of clang-format does if you don't specify anything and don't have any .clang-format file). The problem should therefore be fixed. I pushed it to the Marketplace as version 0.6.0. Thanks for your help!
