### ISSUE TITLE
Formatting using Regroup unstable.

### ISSUE THREAD

**Issue by HuskyNator** [xaverh/vscode-clang-format-provider#108]
Whenever I use a format style that uses `IncludeBlocks: Regroup`, such as Google, a newline keeps being added and removed after the imports. (Each time i format)

Im not sure if this is a clang problem or something else, appreciate every comment/advice.

**Comment by guigarma** [comment]
Do you have steps to reproduce? So far for me everything is in working order. Make sure to include categories and assign priorities:

IncludeBlocks: Regroup
IncludeCategories:
## Project includes
- Regex: '^<my_library\.h>'
  Priority: 1
- Regex: '^<internal/*'
  Priority: 2
## Standard library includes
- Regex: '^<std[^/]*>'
  Priority: 3
  
  Sometimes it you run it again will trim the extra white-space after includes, but that has to do with clang-format itself.

**Comment by HuskyNator** [comment]
Have not had issues since, though I do not use clang a lot anymore.
