### ISSUE TITLE
Enable clang-format for JavaScript & TypeScript?

### ISSUE THREAD

**Issue by mprobst** [xaverh/vscode-clang-format-provider#11]
`clang-format` does an IMHO pretty nice job on formatting JavaScript and TypeScript. Unlike the TS built in formatter, it doesn't just format, but actually reflow the code.

What do you think of adding an option to use `clang-format` for JS & TS, too?

**Comment by martine** [comment]
I have a fix for this, blocked on #13

**Comment by xaverh** [comment]
Fixed in #15
