### ISSUE TITLE
Format just the current statement?

### ISSUE THREAD

**Issue by mprobst** [xaverh/vscode-clang-format-provider#12]
If you run `clang-format` and give either just `-cursor`, or a empty range at the  current cursor, `clang-format` only formats the current statement, which is quite nice for interactive editing, in particular in a large document where you might not want to modify the rest of the doc (e.g. might not be properly formatted and you want to avoid the edits).

Does VS Code's API support such a use case? Would it make sense to add a keybinding for this?

**Comment by xaverh** [comment]
This works out of the box now since Visual Studio Code 1.7 provides a "Format selection" command which formats only the selected statement.
