### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by martine** [xaverh/vscode-clang-format-provider#13]
I have a branch that fixes some bugs in this code, but to make a contribution to this library I need the code to be available under an open source license.

It appears the MS sample extension uses the MIT license:
https://github.com/Microsoft/vscode-extension-samples/blob/master/LICENSE

**Comment by martine** [comment]
It looks like you intended MIT license (that's what the package.json says), so I think you just need to check in a LICENSE file.

**Comment by xaverh** [comment]
Indeed, like the marketplace page suggests this is intended to be released under the MIT license.
