### ISSUE TITLE
Don't override clang-format default formatting

### ISSUE THREAD

**Issue by evmar** [xaverh/vscode-clang-format-provider#16]
Currently this extension hardcodes LLVM formatting as the fallback default:
https://github.com/xaverh/vscode-clang-format-provider/blob/a9b149ab3d3b7b615ed7d1fbbd80b0aaa56e9f14/package.json#L48

It's not clear why the extension includes this.  Why not leave it empty?

**Comment by xaverh** [comment]
Actually, "LLVM" is the default fallback in clang-format (cf. https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/ClangFormat.cpp). If you left this empty, you would get an error message. If you chose "none" as default, you would get non-standard behaviour.

**Comment by evmar** [comment]
Ah, the Google-internal version of clang-format apparently modified the default setting.
