### ISSUE TITLE
clang-format should use google style for JS

### ISSUE THREAD

**Issue by evmar** [xaverh/vscode-clang-format-provider#18]
According to the clang-format JS maintainer, they haven't tuned clang-format's LLVM style for JS.

So, for example, the LLVM style makes object literals look weird:

```sh
sigint:~$ cat foo.js
var x = { foo: 3 };
sigint:~$ clang-format -style=llvm foo.js
var x = {foo : 3};
sigint:~$ clang-format -style=google foo.js
var x = {foo: 3};
```

How would you feel about a patch to make "google" the default fallbackStyle for JS/TS?

**Comment by mprobst** [comment]
(co-maintainer of the JS part of clang-format here)

+1 to what Evan says, clang-format only does meaningful things to JavaScript/TypeScript with `-style=google`. I think the best bet is to always run with `-style=file -fallback=google` on JS & TS files.

**Comment by xaverh** [comment]
OK, I changed it to "google", the results are quite convincing. I will push it to Visual Studio Marketplace tomorrow.

**Comment by evmar** [comment]
Thanks Xaver!
