### ISSUE TITLE
workspace-local clang-format binaries

### ISSUE THREAD

**Issue by rictic** [xaverh/vscode-clang-format-provider#19]
When a new version of clang-format is released it may change formatting. One way to manage this is to manage clang-format as a dev dependency in each project. Using `npm` for example, `npm install clang-format` will put the `clang-format` binary at `workspace-path/node_modules/.bin/clang-format`.

It would be nice to be able to configure this plugin with a workspace-local path (i.e. relative to the cwd of the workspace) to the `clang-format` executable. If you'd accept a PR for this I'm willing to take a shot at it.

**Comment by xaverh** [comment]
Sure. Interesting idea.
