### ISSUE TITLE
Can't get formatting to work

### ISSUE THREAD

**Issue by mschuckmann** [xaverh/vscode-clang-format-provider#20]
I'm on Ubutun 15. 
I have clang-format version 3.4.2 installed
I have VSCode 1.3.1

I have added the following to my vscode settings.json file:
  "clang-format.language.cpp.enable": true,
  "clang-format.language.c.enable": true,
  "clang-format.language.c.style": "LLVM",
  "clang-format.language.cpp.style": "LLVM",
  "clang-format.language.c.fallbackStyle": "LLVM",
  "clang-format.language.c.fallbackStyle": "LLVM"

I try to run the "editor.action.format" command which appears to be bound to ctrl+shift+i and I get nothing. 
What am I missing or doing wrong?

**Comment by mschuckmann** [comment]
Update: 

If I run the format command by entering the command pallete ctrl+shift+p and select "Format Code" I get the following error: "Cannot format due to syntax errors"

This occurs with the simplest of code: 

```
int main(int argc, char** argv)
{
return 0;
}
```

**Comment by xaverh** [comment]
The syntax error is not in your code. Actually, clang-format does not support --fallback-style="LLVM" before version 3.6.0. Since the --fallback-style option currently always gets passed to clang-format, you need at least clang-format 3.6.0 to use this extension.

**Comment by mschuckmann** [comment]
That works thanks.
