### ISSUE TITLE
Not working anymore with VSCode 1.5.2

### ISSUE THREAD

**Issue by jhasse** [xaverh/vscode-clang-format-provider#22]
Since updating to VSCode 1.5.2 Clang-Format (v0.10.3) doesn't work anymore: Selecting `Format Code` does nothing, no error message or anything.

```
$ clang-format --version
clang-format version 3.8.0 (tags/RELEASE_380/final)
$ uname -r
4.7.2-201.fc24.x86_64
$ code --version
1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b)
```

**Comment by xaverh** [comment]
Do you use the [Microsoft C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) (or another extension that is providing a formatter for the programming language you are using clang-format for)?
If so, does it work if you disable the other extension? I already reported this problem to the Visual Studio Code team: https://github.com/Microsoft/vscode/issues/11609

**Comment by jhasse** [comment]
Yes, that seems to be the problem :)

**Comment by maxence-charriere** [comment]
this doesn't work for me.

**Comment by xaverh** [comment]
Sure, because https://github.com/Microsoft/vscode-cpptools/issues/303 is not fixed yet. There is nothing this extension can do to solve this issue.

**Comment by maxence-charriere** [comment]
so actually, it's just that the key binding changed in the last version.

Here is the one to use:
```
editor.action.formatDocument
```
