### ISSUE TITLE
Adopt format on save changes

### ISSUE THREAD

**Issue by jrieken** [xaverh/vscode-clang-format-provider#23]
Just a quick heads up on this: https://github.com/xaverh/vscode-clang-format-provider/blob/master/src/extension.ts#L236

For our September release we have added  an event `onWillSaveTextDocument` and also a new option `formatOnSave` which invokes known formatters before saving to disk. So the ugly workaround should not be needed anymore. Details are [here](#239), [here](#12449), and [here](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md)

**Comment by xaverh** [comment]
Thanks, that's good news. I'll have a look at this in the next days.

**Comment by xaverh** [comment]
I tested it on the insider release and it worked great. As soon as it is tested on the final 1.6.0, it will be pushed to marketplace.

**Comment by jrieken** [comment]
Great. Thanks for looking in to this

**Comment by xaverh** [comment]
Update is available here as well as in the VS Marketplace.
