### ISSUE TITLE
Using a file to specify the format style

### ISSUE THREAD

**Issue by smac89** [xaverh/vscode-clang-format-provider#28]
I tried using a file to add formatting by placing a file called `.clang-format` under `$(HOME)/.config/Code/User`.

This does not seem to work because the formatting is different from what I have given.

How should I go about specifying the file I want to use?

**Comment by xaverh** [comment]
Clang-Format searches for the configuration file in your project directory first. If it does not find it there it goes recursively up the directory tree until it does. If it does not find a .clang-format file, it uses the default style.
If you want to change that behavior you can make use of the `clang-format.style` setting.
You can either pass it your file name or a prefered default style or a JSON formatted list of options like {key1: value1, key2: value2, ...} (cf. http://clang.llvm.org/docs/ClangFormatStyleOptions.html).
