### ISSUE TITLE
NPM-provided clang-format cannot be specified on Windows

### ISSUE THREAD

**Issue by rizadh** [xaverh/vscode-clang-format-provider#29]
On a Windows machine with `clang-format` installed through NPM at `C:/Users/MyName/myProject/node_modules/.bin/clang-format`.

I set the correct path to the executable in VS Code's settings.
```
"clang-format.executable": "C:/Users/MyName/myProject/node_modules/.bin/clang-format"
```

However, the plugin is still looking for `clang-format.exe` (which doesn't exist) instead of `clang-format` (which is installed).

The plugin should attempt to find the provided executable without the `.exe` appended, even on Windows machines.

The same situation occurs when a `clang-format` executable is available globally (installed via `npm install -g clang-format`)

This is not a duplicate of #19 since that did bug did not pertain to the plugin's automatic appending of `.exe` but rather the ability to specify placeholders.

**Comment by xaverh** [comment]
Thanks, should be available in the Marketplace any minute.
