### ISSUE TITLE
Visual studio code + xaver.clang-format has no effect under Linux

### ISSUE THREAD

**Issue by sylwa06** [xaverh/vscode-clang-format-provider#31]
Clang-format VS code pluggin is running but does'nt make the job at all on my linux system.
Exactly the same approach works nicely under Windows 10.

I've installed VS code 1.9.1 along with the Clang-Format pluggin 1.1.1 under a scientific linux :

```
> uname -a
> Linux matis 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 06:09:11 CST 2016 x86_64 x86_64 x86_64 GNU/Linux)
```

My settings.json looks to be properly set up :

```
{
    "window.zoomLevel": 1,
    "editor.formatOnSave": true,
    "editor.tabSize": 2,
    "extensions.autoUpdate": true,
    "clang-format.style": "LLVM"
}

```
But nothing occurs when saving a .h or .C code file...

I did the exactly same approach under Win10 and it works smoothly.

May I ask you some hints please ?

All the best

Sylvain

**Comment by xaverh** [comment]
Which version of LLVM are you using? Scientific Linux are, as far as I know, unfortunately shipping the somewhat outdated version 3.4, which does not accept some of the options the extension is passing to the clang-format binary (cf. #20). Can you try using clang-format 3.6 or higher?

**Comment by sylwa06** [comment]
Hi Xaverh !
Many thanks for your answer.
You're right, the llvm version installed is 3.4.2-8.
I'am a bit confused with the llvm download page, may I ask you which approach should I follow to install properly clang on my scientific linux : a pre-built library ? apt get (but it sounds like it is dedicated to debian or ubuntu) ?
I've used yum with the epel 7 repo and I've obtained the version 3.4.

With best Regards

Sylvain

**Comment by xaverh** [comment]
Hi Sylvain,

you could either try to install the Fedora package (which might or might not work) or download a prebuilt package from llvm.com (for this extension to work, you only need the clang-format binary, which you can put on any place on your hard drive and tell the extension where you put it through the `clang-format.executable` option. You could compile a recent version of LLVM/Clang yourself (the hard way) or you could install a recent version of clang-format through e.g. npm (also requires `clang-format.executable`setting).
I hope this helps, best regards,

Xaver

**Comment by sylwa06** [comment]
Hi Xaver,
Thanks for your hints, I gonna give it a go and let you know what's happened.
All the best
Sylvain
