### ISSUE TITLE
Show clang-format errors

### ISSUE THREAD

**Issue by stevefolly** [xaverh/vscode-clang-format-provider#33]
Sometimes I might have an error in my `.clang-format` file and it doesn't format as I'd expect.  If I use `clang-format` on the command line, I see the errors.

Is it possible to capture any `clang-format` errors to the output window in VSCode?

**Comment by xaverh** [comment]
This sounds like a useful feature and I think this should be possible, I'll have a look in this.

**Comment by xaverh** [comment]
One problem here is that clang-format unfortunately does fail silently in case of syntax errors. Even if -fallback-style=none it returns 0 and does not format at all.
cf. https://reviews.llvm.org/D27440
Maybe there are other ways to achieve this...
