### ISSUE TITLE
Please install [clang](http://clang.llvm.org/) or check configuration `clang.executable`

### ISSUE THREAD

**Issue by SeakyLuo** [xaverh/vscode-clang-format-provider#39]
I got this error message after I updated the latest vscode.
Then I can see it all the time even I close it for a thousand times.
I think I have installed all the plugin I need.
How do I fix it or disable it?
I can't disable it by commenting that part of codes. 
It is really annoying.
![image](https://cloud.githubusercontent.com/assets/25042708/25300086/8d75794e-26bc-11e7-8595-15a9a7d4d85a.png)
I have reported to vscode-cpptools and they tell me to come here.
Thanks!

**Comment by xaverh** [comment]
The clang-format extension does not automatically install the formatter, it assumes that you have it installed already.
As sean-mcmanus said in https://github.com/Microsoft/vscode-cpptools/issues/647, the best way to achieve this, is to download the LLVM compiler at http://releases.llvm.org/download.html and to put the install location to your environment variable "Path". If you prefer to not have LLVM in your Path variable, you could instead point "clang-format.executable" in your settings to the exact location of the executable (clang-format.exe on Windows).
Or if you have https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools installed anyway, you could also switch to using their bundled version of clang-format.
I hope this helps, feel free to reopen the issue, if there are still any questions.

**Comment by SeakyLuo** [comment]
I think my "clang-format.executable" points to the correct thing. And I have alreadey installed https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools , but that issue still exists. Actually that problem doesn't occur every time I use it. I just open a cpp file but that problem disappeared temporarily. But when it arises, it becomes really annoying if I want to switch tags.
![image](https://cloud.githubusercontent.com/assets/25042708/25320644/c49ed882-285d-11e7-8dff-bde561ec3d37.png)

**Comment by xaverh** [comment]
Does formatting work on your C++ files?
What happens if you type `clang-format` in your terminal? Does it find an executable?
Do you use https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools for formatting? (i.e. what's your settings for `"C_Cpp.formatting"`?)
What am I supposed to see on that second screenshot besides an overview of the default settings?

**Comment by SeakyLuo** [comment]
Format works for me. And I have enabled https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools .
You said I could point "clang-format.executable" in settings to the exact location of the executable (clang-format.exe on Windows). And the line of the screenshot shows it is points to the clang format.
And I found the clang-format executable.
![image](https://cloud.githubusercontent.com/assets/25042708/25358839/b49b30bc-28f7-11e7-84b8-0d4a25a87f39.png)

**Comment by liliasouma** [comment]
hi , download  llvm from http://releases.llvm.org/download.html install and check that make path for all users then ran vscode as administrator it work for me now

**Comment by xaverh** [comment]
@SeakyLuo This extension and https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools are not requirements for each other. If anything they are somewhat conflicting. That is, you cannot run both formatters at the same time. Basically if formatting works for you and you have not set the path for clang-format for this extension, you are already using https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools and you do not need this extension at all. You could try to disable https://marketplace.visualstudio.com/items?itemName=xaver.clang-format and see if formatting still works for you.
@liliasouma running the editor as administrator should not be necessary and should be avoided. Does your user account have access rights for the directory you installed clang-format into? And have you tried to manually set `"clang-format.executable": "D:\\Program Files\\LLVM\\bin\\clang-format.exe"`?
