### ISSUE TITLE
Add excludes for files/directories

### ISSUE THREAD

**Issue by andyreimann** [xaverh/vscode-clang-format-provider#43]
Hi,
I really like this extension and want to use it in our entire project, however as we are also sometimes working on source code that we cannot run clang-format on, I'd like to exclude that specific folder in the settings.
For me it's not an option to just manually run it through the command palette.

Would you consider to add a setting, basically a list of files, paths or regexes to not run clang-format on when formatOnSave is used?

Best,
Andy

**Comment by xaverh** [comment]
Hi,
do you like to ignore files in a all files in a subfolder of the open folder? Then, you could put a ```.clang-format``` file into the subfolder with the following content:
```yaml
DisableFormat: true
```
For everything more complicated we do need a new setting. I guess, this is something that could be done. I'll have a look into this, when I have time.
Pull requests are welcome, too :-)

**Comment by andyreimann** [comment]
Nice thanks! putting a separate .clang-format in the folder solved my issue.
In my case it was not even a sub folder, but a folder that is not even in my workspace folder.
I guess it would just work the same way with a sub folder.

Thanks again :)
