### ISSUE TITLE
Map initializer syntax issue " => "

### ISSUE THREAD

**Issue by dimitrisuls** [xaverh/vscode-clang-format-provider#44]
Hi,

Thanks again for this great plugin ;).
I'm not sure if this is the right place to post this issue. It probably belongs in the clang-format repo itself - which I can't seem to find.

Anyway.
When I format a file with the following code:

````
Map<String, Object> testMap = new Map<String, Object> {
    'testA' => 20,
    'testB' => 'Cat'
};
````

It adds an extra space between the equals and greater than. Like so:

````
Map<String, Object> testMap = new Map<String, Object> {
    'testA' = > 20,
    'testB' = > 'Cat'
};
````

This causes my code to not compile anymore.
Is there any way to fix this?

**Comment by xaverh** [comment]
Probably not, because this is not valid syntax in any of the officially supported languages (C++, JS, Java, Obj-C, Protobuf), so clang-format does not know how to handle this. You can try to report this upstream... http://llvm.org/
