### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by joa-quim** [xaverh/vscode-clang-format-provider#45]
Hi,
Installed this and it simply doesn't work. But more, if my ``.clang-format`` file has an error that I get an error message and changes are made to file, probably till the error situation is reached. Correcting the  ``.clang-format`` gets me to the beginning, that is nothing is changed.
Running the `` ``.clang-format`` from the command line works file, so clearly VSC issue.

Ah, and Windows10 here.

**Comment by xaverh** [comment]
What are your settings? Which version of clang-format are you using? And do you have other, possibly conflicting extensions installed (e.g. https://marketplace.visualstudio.com/items/ms-vscode.cpptools)?

**Comment by joa-quim** [comment]
````
clang-format -version
clang-format version 3.7.0 (tags/RELEASE_370/final)
````

and yes, I have cpptools installed. Hadn't noticed that cpptools also has
clang-format

**Comment by xaverh** [comment]
Have you set ```"C_Cpp.formatting": "Disabled"```?

**Comment by joa-quim** [comment]
No I hadn't (some doc I missed reading?) but it makes no difference. I even disabled the whole cpptools and still nothing.
I have ``.clang-format`` files in either the file's directory and in its parent dir. Contrary to what seams to be indicated in clang-format the one in the file's dir is the one that is used but from within VSC nothing happend when I do a ``Alt+Shift+F`` (or right-click and select "Format Document")

**Comment by xaverh** [comment]
The ```.clang-format``` in the directory of the source code is preferred. This is normal behaviour. Have you tried to set ```clang-format.executable``` manually?

**Comment by joa-quim** [comment]
That is not the source of the problem (I have llvm in my path). Remember
that I said that if there is an error in the ``.clanf-format`` file than I
see it being executed. For example by setting
"BreakBeforeBraces: Custom"

which apparently is only supported in 3.8 (and for Windows only 3.7 is
available), than I get this error, which proves that it is run.

YAML:28:20: error: unknown enumerated scalar
BreakBeforeBraces: Custom
                   ^~~~~~
Error reading c:\progs_cygw\GMTdev\gmt5\5.4\src\mb\.clang-format: invalid
argument

**Comment by xaverh** [comment]
Well, now I am clueless, tbh.
Have you tried to run the extension in debug mode to see where it hangs?

PS: I don't assume this is relevant for this issue, but there is even LLVM 4.0 for Windows: http://releases.llvm.org/download.html#4.0.0

**Comment by joa-quim** [comment]
> Well, now I am clueless, tbh.

Never mind, I know that feeling.

> Have you tried to run the extension in debug mode to see where it hangs?

I'm a bit busy now to learn how one more debug technique but for future use, how would I do that?

And thanks for the 4.0 link. I had followed another link that directed me to 3.7. Now I can do the ``BreakBeforeBraces: Custom``, even if manually.

**Comment by xaverh** [comment]
I just realised I was wrong, it actually does matter. In the last release we introduced the assume-filename option, which is only available to clang-format 3.8 and higher. Can you try to update and verify this?

**Comment by xaverh** [comment]
To debug the extension you need to pull this repo and open it in VS Code.
Then, you run either `npm install` or `yarn` to install the dependencies.
Then, you can run it with F5.

**Comment by joa-quim** [comment]
I did test with 4.0. Unfortunately continue not working.
Thanks for the debug info. When I have more time I may try it.

Thanks
