### ISSUE TITLE
Format current line when there is no selection

### ISSUE THREAD

**Issue by kashev** [xaverh/vscode-clang-format-provider#46]
Is there any way to run the formatter on the current line? Right now, to do so, I have to select one or more characters on the line to run the formatter, when I'd like to just hit a shortcut key.

**Comment by kashev** [comment]
Is this solved by #12? It doesn't seem to work as indicated it should in that issue.

**Comment by jhasse** [comment]
No, "Format Selection" is only available when something is actually selected.

**Comment by xaverh** [comment]
Has been fixed upstream, cf. https://code.visualstudio.com/updates/v1_29#_format-selection
