### ISSUE TITLE
Wrongly formatting 'vector<vector<int> >' as 'vector<vector<int>>'

### ISSUE THREAD

**Issue by svenhsia** [xaverh/vscode-clang-format-provider#47]
The auto formatting seems to be unable to distinguish nested angle brackets and double arrows, as shown in title.

Actually, I noticed no such problem with my last installation of VS Code and Clang-format. However, after an re-installation, this problem appears.

Did anyone else run into the same problem ? Any known solutions ?

Thanks in advance.

**Comment by xaverh** [comment]
This is not really an issue of this extension rather than upstream clang-format. Have you tried settings `"Standard"` to `"Cpp03"` in your config (cf. http://clang.llvm.org/docs/ClangFormatStyleOptions.html)?
