### ISSUE TITLE
rearranges include files even when Sort Includes = False

### ISSUE THREAD

**Issue by robotjunkyard** [xaverh/vscode-clang-format-provider#49]
I set this setting to False but clang-format still likes to automatically rearrange the order of #includes in my source files on save.

**Comment by xaverh** [comment]
Does it do the right thing if you invoke clang-format manually instead of through the extension?

**Comment by robotjunkyard** [comment]
Just running clang-format.exe on any of my .cpp files as-is from the command line, does not mess with the order of include files.

**Comment by SoftwareApe** [comment]
Can confirm, noticed the same behavior. This is terrible in a legacy codebase where you're not so sure if the sorting of the includes might break something.

**Comment by xaverh** [comment]
@robotjunkyard Can you confirm that this problem occurs when you disable the "C/C++ extension"?

**Comment by robotjunkyard** [comment]
@xaverh under VS2015's Extensions & Updates window, I do not see any extension or plugin listed anywhere with C or C++ in its name

**Comment by robotjunkyard** [comment]
and with a sudden sinking feeling in my gut, I think I just now realized I might not even be using the same clang-format plugin this github page is about.  this is for that bare-bones Visual Studio Code editor, isn't it?

**Comment by xaverh** [comment]
Indeed, it is.

**Comment by robotjunkyard** [comment]
my apologies, I'll close this
