### ISSUE TITLE
Marketplace package is not up to date

### ISSUE THREAD

**Issue by ioachim** [xaverh/vscode-clang-format-provider#5]
As you have merged my changes, I unpublished my version from the marketplace. For any future additions I make to this, I'll make a pull request for you.

I see that the package on the marketplace is not up to date (It doesn't have mine or @owt5008137 changes). Could you publish a new version? Thanks!

**Comment by xaverh** [comment]
Thanks a lot for your changes to the package. I published the new version to the marketplace.
