### ISSUE TITLE
How to configure space in the import syntax in TypeScript?

### ISSUE THREAD

**Issue by doggy8088** [xaverh/vscode-clang-format-provider#50]
In the TypeScript file, all the `import` syntax will be formated like this using [Clang-Format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format):

```
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
```

I'd like to change to this because the **TSLint**'s default rule including **import-spacing** default value to **true**:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
```
Is it possible to config this in the [Clang-Format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) extension or in the [clang-format](https://www.npmjs.com/package/clang-format)?

**Comment by xaverh** [comment]
Anything regarding the configuration of the formatting has to be done in the clang-format config.
