### ISSUE TITLE
Problems about format error and rule

### ISSUE THREAD

**Issue by CodeFuckerZhao** [xaverh/vscode-clang-format-provider#56]
I am a C++ coder, when I input the `std::vector < vector <int> > _varname` the plugin will format it to `std::vector<vector<int>> _varname`. When `> >`turns to `>>`, G++ will consider it as a stream operator and returns a "Compile Error", what should I do?
And How can I fix its rules to Google C++ Guide?
I am looking forward to hearing form you. Thank you very much indeed.

**Comment by xaverh** [comment]
You need a file with the name `.clang-format` in your project directory with the following content:
```
---
BasedOnStyle: Google
Standard: Cpp03
...
```
For more details refer to https://clang.llvm.org/docs/ClangFormatStyleOptions.html.
Hope that helps.
