### ISSUE TITLE
editor.formatOnSave is not working.

### ISSUE THREAD

**Issue by hibumbapartha** [xaverh/vscode-clang-format-provider#57]
My Typescript file is not being formatted, while my HTML files is being formatted at the time of save.

But if I try Right Click -> Format Document, then it is being formatted.

**User Settings**
  {
    "html.format.wrapLineLength": 150,
    "html.format.wrapAttributes": "force-aligned",
    "tslint.autoFixOnSave": true,
    "window.zoomLevel": 0,
    "editor.renderControlCharacters": true,
    "clang-format.executable": "C:/Users/MyId/AppData/Roaming/npm/clang-format",
    "editor.formatOnSave": true
  }

**Visual Studio Code**
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T16:16:25.767Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by xaverh** [comment]
Can you test if it works with `"tslint.autoFixOnSave": false`?

**Comment by hibumbapartha** [comment]
It is not working with "`tslint.autoFixOnSave": false` also

**Comment by nicksay** [comment]
I see the same problem in C++ as well.

**Comment by nicksay** [comment]
Ah, for C++ it was the same formatting priority conflict issue as before.  Setting `"C_Cpp.formatting": "Disabled"` to disable the default formatting fixed it for me.

**Comment by xaverh** [comment]
@hibumbapartha Does it work if you disable the TSLint extension entirely?

**Comment by calebegg** [comment]
I also have this problem. Nothing happens when I save, but shift+alt+F works fine. Other files format on save fine.

I do not have the TSLint extension, or any other extensions.

Is there anything I can do to help debug/diagnose?

**Comment by xaverh** [comment]
Have you tried using the ```clang-format.assumeFilename``` option?

**Comment by xaverh** [comment]
Close due to inactivity > 1y.
Feel free to re-open if problem persists.
