### ISSUE TITLE
Got error for IncludeIsMainRegex

### ISSUE THREAD

**Issue by intijk** [xaverh/vscode-clang-format-provider#58]
In my `.clang-format` file, I have such a line

```
IncludeIsMainRegex: '$'
```
When I format the code with short cut `ctrl+shift+I`, it gives me below error:

```
YAML:57:21: error: unknown key 'IncludeIsMainRegex'
IncludeIsMainRegex: '$'
```

**Comment by xaverh** [comment]
Does it work if you launch clang-format in the terminal? Which version of clang-format (`clang-format --version`) are you using on which OS?

**Comment by intijk** [comment]
Sorry for the delay.
This is my issue. This feature requires clang format 4.0 or higher. Update it solved the case. Please close.
