### ISSUE TITLE
Output "Invalid value -style" while formatting

### ISSUE THREAD

**Issue by suparodi** [xaverh/vscode-clang-format-provider#59]
Hello,

I've got a message on the 'Output' window saying `Invalid value -style` while formatting a c++ file.

I am using vscode on macOS HS and I have set these two parameters:

`"clang-format.executable": "/usr/local/Cellar/clang-format/2017-11-14/bin/clang-format",
    "clang-format.style": "~/.clang-format",`

And here is my `.clang-format` file:

[clang-format.txt](https://github.com/xaverh/vscode-clang-format-provider/files/1667556/clang-format.txt)

version of clang-format : 2017-11-14.
version of vscode : 1.19.3.

**Comment by xaverh** [comment]
`"clang-format.style"` forwards its value to the `-style=` command line parameter, i.e. if you want to provide your options directly you can do something like `-style='{key1: value1, key2: value2, ...}'` or you can set it to `-style=file`and put style configuration in the .clang-format or _clang-format file in the project directory.
When using `-style=file`, clang-format for each input file will try to find the .clang-format file located in the closest parent directory of the input file. When the standard input is used, the search is started from the current directory.
This is the default behavior, i.e. you can try leaving the "clang-format.style" option out entirely.

**Comment by suparodi** [comment]
Understood thank's a lot, so I can't use a default .clang-format in $HOME ?

**Comment by xaverh** [comment]
Yes, just leave the setting `"clang-format.style"` out of your settings.json entirely. It should work with the defaults for you.

**Comment by suparodi** [comment]
Indeed, problem solved. Thank you very much !
