### ISSUE TITLE
Clang-format hangs forever in latest release

### ISSUE THREAD

**Issue by willdzeng** [xaverh/vscode-clang-format-provider#64]
Issue Type: <b>Bug</b>

Clang-format hangs forever in latest release.
![image](https://user-images.githubusercontent.com/12994633/39886188-8b262b92-5443-11e8-9511-7678fddeca23.png)

Use foramt-on-save, clang-format-5.0.
Tried to reinstall VSCode, and it works for a couple of times, then hangs again.
Not sure if it's an issue in VSCode or extension,
could be great if someone can help me out.

Extension version: 1.6.2
VS Code version: Code 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45, 2018-05-03T15:23:19.356Z)
OS version: Linux x64 4.8.0-56-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 3499)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.63GB (5.53GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by tiagomlalves** [comment]
Hi,

I had the same issue. I've noticed the clang-format version being used was the one under:
`:~/.vscode/extensions/ms-vscode.cpptools-0.17.0/LLVM/bin`

As a hack, I're renamed `clang-format` to `clang-format.bak` and created a symbolic link to my clang-format version: `/usr/local/bin/clang-format`.

It's working now...

**Comment by willdzeng** [comment]
Thanks @tiagomlalves 
looks like it's also fixed in 1.23.1, doesn't hang anymore, will keep this issue and confirm fixed in a week.
