### ISSUE TITLE
Extension host terminated unexpectedly when pasting/formating code 

### ISSUE THREAD

**Issue by apingault** [xaverh/vscode-clang-format-provider#66]
Hello

Since last week,  when I paste code in a c or c++ the `extension host` would crash (not all the time but often enough to be annoying). The crash also happens (but seems to be less often) when I use the `Format Document` command. 
![screen shot 2018-07-30 at 17 50 00](https://user-images.githubusercontent.com/11057316/43408203-fc42b5b2-9420-11e8-9dd2-610a81f7fcfb.png)

The problem is related to the formatting process of your extension:
 - No more crash when I disable this extension or disable the formatting for the given language.  
 - No more crash on pasting when disabling `editor.formatOnPaste`
 - No crash on other formats (tried on python and HTML)

I've already tried disabling all other c/c++ related extension installed to isolate the problem. 
Funny thing is I have the `editor.formatOnType` set to `true` and formatting does happen properly without any crash whenever I hit `;` for example.

I don't have much more information from the debug console:
![screen shot 2018-07-30 at 17 12 57](https://user-images.githubusercontent.com/11057316/43406904-885068c8-941d-11e8-9118-75234fc140a2.png)

I am using the latest insider build (`1.26.0 - dae69dbf00357ff8a3fe740a1f211d66b0b4681c`) on OSX 10.13.6

Do you have any idea what could be the problem?

Cheers

**Comment by xaverh** [comment]
Does this problem occur on the release version, too? Please feel free to reopen the issue if it does.
