### ISSUE TITLE
Configuration file(s) do(es) not support C++ error with TypeScript in VS Code

### ISSUE THREAD

**Issue by gregbown** [xaverh/vscode-clang-format-provider#67]
I am getting this error in VS-Code. It occurs in any TypeScript file. Using "typescript": "^2.9.x",
I have a [local .clang-format file](https://gist.github.com/gregbown/8b96293072565bd5b6cf659c8357dd68)
I also tried reducing the file to just declaring BasedOnStyle: Google

Windows 10
VS-CODE
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Using this Clang Format plugin

Appreciate any direction towards resolving this
Thank you

**Comment by xaverh** [comment]
Have you tried using the ```clang-format.assumeFilename``` option?

**Comment by xaverh** [comment]
Closed due to inactivity 1y+.
Feel free to reopen if problem persists.
