### ISSUE TITLE
Extention adds to the "Problems" tab

### ISSUE THREAD

**Issue by mheden** [xaverh/vscode-clang-format-provider#68]
Fore some reason, when I enable this extension I get entries added to the "Problems" tab for my code base.

I only like to use `clang-format` for actually formatting my code (I use GCC for building). Is there a way of disabling any analysis of the code?

**Comment by xaverh** [comment]
Can you post an example entry? Afaik this extension is not supposed to post anything to the problems tab and has no means of performing code analysis.

**Comment by mheden** [comment]
I'm not able to reproduce, probably a problem with my installation.
