### ISSUE TITLE
Clang error

### ISSUE THREAD

**Issue by rekib0023** [xaverh/vscode-clang-format-provider#71]
- Extension Name: clang-format
- Extension Version: 1.6.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 220,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:c"
	}
}
```

**Comment by xaverh** [comment]
What exactly is the error? What does happen resp. does not happen?
