### ISSUE TITLE
LLVM of ms-vscode.cpptools is used

### ISSUE THREAD

**Issue by mjvk** [xaverh/vscode-clang-format-provider#73]
It seems that a .clang-format is somehow parsed using the LLVM version included by the ms-vscode extension. This version is older which results in errors such as the one below as this is only supported in newer versions. The formatting works in the end though, so besides a formatting failed output message that is unnecessary functionality is not impacted.

Formatting failed:
"c:\Users\mjvk\.vscode\extensions\ms-vscode.cpptools-0.19.0/bin/../LLVM/bin/clang-format.exe" -style="file" -fallback-style="LLVM" -assume-filename="c:\Soft_Dev\590008\JLSCONTROL\JLSOCSOURCE\MASTER\CORE\src\MAIN\JLS\TLB\MHS\MHSblock\MHSwinch\MHSwinch.cpp"
  YAML:20:34: error: invalid boolean
  AlwaysBreakTemplateDeclarations: Yes
                                   ^~~
  Error reading c:\Soft_Dev\590008\JLSCONTROL\JLSOCSOURCE\.clang-format: invalid argument

**Comment by xaverh** [comment]
Can you report what happens if you deactivate (but not remove) the MS C++ Tools extension?

**Comment by xaverh** [comment]
Issue closed due to inactivity. In all likelihood this can be solved by setting ```"clang-format.executable"``` manually.
