### ISSUE TITLE
Does not work when the working directory is ssh filesystem

### ISSUE THREAD

**Issue by kwinz** [xaverh/vscode-clang-format-provider#74]
Does not work when the working directory is ssh filesystem.
I am using https://github.com/SchoofsKelvin/vscode-sshfs
Neither the command `>Format Document`, nor the setting `"editor.formatOnSave": true` work.
If I edit something on the local harddisk everything works as expected.
Also the `vcode-sshfs` works as expected in every other case.

**Comment by kwinz** [comment]
See also https://github.com/SchoofsKelvin/vscode-sshfs/issues/72

**Comment by xaverh** [comment]
I cannot really test this right now, b/c I'm not working on Windows these days. But it looks like this issue is outside of the scope of this extension. Does "Format on Save" work with other formatters (eg prettier, the built-in one, etc) on remote files?

**Comment by xaverh** [comment]
Since clang-format does not understand how to handle vscode-sshfs and this extension just passes the formatting to clang-format this is not fixable by this extension.
