### ISSUE TITLE
conflict with prettier

### ISSUE THREAD

**Issue by wayou** [xaverh/vscode-clang-format-provider#75]
With both clang-format and prettier installed will cause inconsistent result.

![foramt mov](https://user-images.githubusercontent.com/3783096/48334115-81153880-e694-11e8-94d8-b5f150f4d6e7.gif)

**Comment by wayou** [comment]
One possible solution is to add an option like the prettier does: require `.clang-format` to enable format.

<img width="295" alt="screen shot 2018-11-13 at 01 14 32" src="https://user-images.githubusercontent.com/3783096/48363770-a714fa00-e6e1-11e8-805d-22672368843a.png">

**Comment by xaverh** [comment]
I probably just don't get it, but what's the use case for this? Is there any case for doing this instead of just disabling either formatter for a specific language or workspace?

**Comment by wayou** [comment]
Disable either will work on the condition that we know the problem is the conflict. Before I figured this out I've no idea what's going on.

**Comment by xaverh** [comment]
I'm very certain that the problem is the conflict. You are running to extensions that are trying to do the same thing (formatting your source code), but differently.
What's the expected behavior and which problem are you trying to solve running both extensions at the same time?

**Comment by wayou** [comment]
Yep after struggling for a while I figured out it's the conflict. I mean if someone else don't recognize it will also spent time to find out the reason. 

Because one cannot expect what end users have installed so this kind of conflicts are common things(the tslint, eslint, also format code and will conflict with prettier, and there's packages to handle the situation like https://github.com/prettier/tslint-config-prettier, https://github.com/prettier/eslint-config-prettier). So I wonder maybe the extension can do sth. with this. Thought I'm not sure what's the best way to handle the conflict. Just raise the issue here.

**Comment by wayou** [comment]
Got it. Thx the reply.
