### ISSUE TITLE
Restrict plugin to filetypes

### ISSUE THREAD

**Issue by davidnorthetal** [xaverh/vscode-clang-format-provider#80]
Hey,

clang-format just messed up my typescript files and I don't seem to be able to make it stop doing so, tho I don't have a `.clang-format` in the project directory.

AFAIS an option is missing to restrict this plugin for specific filetypes.

Thanks for consideration

**Comment by xaverh** [comment]
Hi,

have you tried
```
"clang-format.language.typescript.enable": false
```
?

Hope that helps, if not I need more info.

Sent from ProtonMail mobile

-------- Original Message --------
On Feb 18, 2019, 10:42, davidnorthetal wrote:

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by davidnorthetal** [comment]
@xaverh are these documented anywhere? - I looked for them initially
