### ISSUE TITLE
Unknown command line argument '-fallback-style=google'

### ISSUE THREAD

**Issue by pluveto** [xaverh/vscode-clang-format-provider#88]
Reproduction:

1. Install clang by yum on CentOS 7.3.
2. Run VSCODE(WSL).
3. Having installed this plugin, press alt+shift+f.

or:
```bash
[root@DESKTOP-T772S7H bt]# clang-format -fallback-style=google
```

Result:

clang-format: Unknown command line argument '-fallback-style=google'.  Try: 'clang-format -help'
clang-format: Did you mean '-warn-stack-size=google'?

I see the usage provide by clang-format is:

-style=<string>           - Coding style, currently supports:
                                LLVM, Google, Chromium, Mozilla, WebKit.
                              Use -style=file to load style configuration from
                              .clang-format file located in one of the parent
                              directories of the source file (or current
                              directory for stdin).

May be this problem is due to the version of clang-format? Will there be a option to decide the command option?

**Comment by xaverh** [comment]
As far as I know, CentOS is not shipping clang, I assume you have clang installed through EPEL. Unfortunately that version is ancient. Their version is 3.4, the current upstream version is 8.0. The required minimum for this extension is 3.6. You can install a more recent version of clang-format e.g. from http://releases.llvm.org/download.html or via npm. If you cannot/don't want to install it globally, you can use the `"clang-format.executable"` option to point the extension to the correct location.
