### ISSUE TITLE
Can not format via ssh: There is no formatter for 'cpp'-files installed.

### ISSUE THREAD

**Issue by mohsenomidi** [xaverh/vscode-clang-format-provider#89]
Hi, 
I am using vscode for my C++ project, i installed the Clang-Format version (1.9.0)  i works fine when i open the file from my local drive.

But i am using "Kelvin Schoofs(SSH FS) version (1.16.2) extension for my remote code on the Linux machine, after opening the C++ file from sshfs work-space, and trying to format my C++ document, it returns "There is no formatter for 'cpp'-files installed."

how can i fix this behavior for remote code "i mentioned again: formatting works properly for local files"

Regards.

**Comment by edwincarlson** [comment]
Try installing clang-format on your remote server.
`sudo apt install clang-format`
