### ISSUE TITLE
Formatting range does not work if no text selected

### ISSUE THREAD

**Issue by mprobst** [xaverh/vscode-clang-format-provider#99]
This might be a VS Code limitation, and related to issue #12 (long closed).

When I have my cursor in an incorrectly formatted statement and just hit the shortcut for formatting a range (e.g. `ctrl-i`), no formatting happens. If I do selected a bit of text on the line and hit `ctrl-i`, the statement (and often surroundings) get formatted.

It appears as if VS Code does not trigger the range formatting if no text is selected. I think it should trigger formatting with a zero length range.

**Comment by Morozov-5F** [comment]
Possibly a duplicate of #46

**Comment by mprobst** [comment]
I can confirm this works now with VS Code 1.41.1 and the clang-format extension in v1.9.0.

**Comment by mprobst** [comment]
(it's odd though that it didn't work when I filed, given it's allegedly fixed since VS Code 1.29, which predates me filing this issue. no idea)
